from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
import uuid


class StringRequest(BaseModel):
    request: str = Field(description="The request to the agent.")


class StringResponse(BaseModel):
    response: str = Field(description="The response to the user's request.")


class StringFeedback(BaseModel):
    feedback: str = Field(description="The feedback to the agent.")


class Draft(BaseModel):
    trajectory_id: str = Field(
        description="The id of the conversation.",
        default_factory=lambda: str(uuid.uuid4()),
    )
    draft: BaseModel = Field(description="The draft generated by the agent.")
    feedback: Optional[BaseModel] = Field(
        description="The feedback to the draft generated by the agent.", default=None
    )
    created_at: datetime = Field(
        description="The timestamp when the draft was created.",
        default_factory=datetime.utcnow,
    )
    usage: dict = Field(description="The usage of the draft.", default_factory=dict)
    id: str = Field(
        description="The id of the draft.", default_factory=lambda: str(uuid.uuid4())
    )
